### ISSUE TITLE
No player found page

### ISSUE THREAD

**Issue by DevRuto** [Zach47/gokzstats#45]
If the player has no pro time, but has a tp time recorded in a certain mode, it will return the No Player Found page.

**Comment by ijust-dev** [comment]
The API returns [] from the query used. Because of this, it is unknown if the name/SteamID searched exists. As such, it would require multiple queries to check if a player exists, has Pro or TP times, and a final query to reduce down to the data we want. If you have suggestions on resolving this, let me know.
